#!/usr/bin/bash

TFCLOUD_VERSION="2.5"
# verify root
ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1
ROOTDIR="$(pwd)"
export ROOTDIR
[ ! -d /backups ] && mkdir /backups

trap '' 2
while :; do
    LGGRN='\033[1;32m'
    BLUE='\033[1;34m'
    GREY='\033[0;37m'
    CYAN=''
    NC='\033[0m'
    clear
    echo -e "${GREY}$(date +'%x %l:%M %p') ${NC}"
    printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
    echo -e "\u2503${BLUE} @ ${NC}`[ -f .envtype ] && cat .envtype || echo -e Not Installed`${NC}"
    printf '\u2503'${LGGRN}' )~ '${NC}'\n'
    printf '\u2503''\u2501''\n'
    printf '\u2503'${GREY}" Space    : $(df -h /backups | tail -1 | awk '{print $4}')"${NC}'\n'
    printf '\u2503'${GREY}" Hostname : $(hostname)"${NC}'\n'
    printf '\u2503'${GREY}" Version  : $TFCLOUD_VERSION${NC}\n"
    printf '\u2503'${GREY}" OSVers   : `cat /etc/redhat-release | cut -d" " -f6`${NC}\n"
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"---\033[0m System"'\n'
    printf '\u2503''\033[1m'" 1.\033[0m Data"'\n'
    printf '\u2503''\033[1m'" 2.\033[0m Containers"'\n'
#    printf '\u2503''\033[1m'" 3.\033[0m Admin"'\n'
    printf '\u2503''\033[1m'" 3.\033[0m Reports"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'" r.\033[0m Readme"'\n'
    printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
    printf '\u2517''\u2501''\n'
	echo -ne "Enter selection: "
	read selection
	case $selection in
	1)
		cd $ROOTDIR/msposbackup
		./MENU
		cd -
		;;
	2)
		cd $ROOTDIR/msposapp
		./MENU
		cd -
		;;
	4)
		cd $ROOTDIR/linuxadmin
		./MENU
		cd -
		;;
	3)
		cd $ROOTDIR/msposreports
		./MENU
		cd -
		;;
	r)
		cat README.md | more
                echo -ne "Press enter to continue..${NC}"
                read
		;;
	x)	exit
		;;
	*) ;;
	esac
done
