#!/usr/bin/bash

[ ! -f .container ] && echo "Nothing running!" && exit
CONTAINER=`cat .container`

#docker container stop $(docker container ps -a -q)
docker container stop $(cat .container)
rm -f .container
#systemctl restart docker

[ -f .shopcode ] && [ -d /home/tfpos-`cat .shopcode` ] && userdel tfpos-`cat .shopcode` && rm -rf /home/tfpos-`cat .shopcode` && rm -rf /var/spool/mail/tfpos-`cat .shopcode`

rm -f ./ipsec.secrets
rm -f ./ipsec.conf
