#!/usr/bin/bash

TFCLOUD_VERSION="2.6"

ROOTDIR="$(pwd)"
export ROOTDIR

SHOPCODE="None"

[ -f ./bin/.container ] && CONTAINER=`cat ./bin/.container`
[ -f ./bin/.posip ] && POSIP=`cat ./bin/.posip`

trap '' 2
while :; do
	clear
    LGGRN='\033[1;32m'                                                                                                                                                                                            
    BLUE='\033[1;34m'                                                                                                                                                                                              
    GREY='\033[0;37m'                                                                                                                                                                                             
    CYAN=''                                                                                                                                                                                             
    NC='\033[0m'                                                                                                                                                                                                  
    clear                                                                                                                                                                                                         
    [ -f ./bin/.shopcode ] && SHOPCODE=`cat ./bin/.shopcode`
    echo -e "${GREY}$(date +'%x %l:%M %p') - $TFCLOUD_VERSION${NC}"
    printf '\u250f''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\u2501''\n'
    echo -e "\u2503${BLUE} @ ${NC}`[ -f ../.envtype ] && cat ../.envtype || echo -e Not Installed`${NC}"
    printf '\u2503'${LGGRN}' )~ Containers'${NC}'\n'
    printf '\u2503''\u2501''\n'
    echo -e "\u2503${GREY} Shopcode : `[ -f ./bin/.shopcode ] && cat ./bin/.shopcode`${NC}"
    echo -e "\u2503${GREY} Status   : `podman container list --noheading | grep $SHOPCODE | sed -e "s/\ \ /~/g" | cut -d~ -f5 2>/dev/null`${NC}"
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"-\033[0mContainers"'\n'
    printf '\u2503''\033[1m'" 1.\033[0m Status"'\n'
    printf '\u2503''\033[1m'" 2.\033[0m Start/Stop"'\n'
    printf '\u2503''\033[1m'" 3.\033[0m Connect"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"-\033[0mVPNs"'\n'
    printf '\u2503''\033[1m'" 4.\033[0m Status"'\n'
    printf '\u2503''\033[1m'" 5.\033[0m Start/Stop"'\n'
    printf '\u2503''\033[1m'" 6.\033[0m Create"'\n'
    printf '\u2503''\033[1m'" 7.\033[0m Delete"'\n'
    printf '\u2503''\n'
    printf '\u2503''\033[1m'"-\033[0mSystem"'\n'
    printf '\u2503''\033[1m'" s.\033[0m Shopcode"'\n'
    printf '\u2503''\033[1m'" i.\033[0m Install"'\n'
    printf '\u2503''\033[1m'" p.\033[0m Purge"'\n'
    printf '\u2503''\033[1m'" r.\033[0m Readme"'\n'
    printf '\u2503''\033[1m'" x.\033[0m Exit"'\n'
    printf '\u2517''\u2501''\n'
	echo -ne "Enter selection: ${NC}"
	read selection
	case $selection in
	1)
		cd $ROOTDIR/bin
		./container_status
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	2)
		cd $ROOTDIR/bin
		[ -f .$SHOPCODE.container ] && time ./stop_container || time ./stage-image
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	3)
		cd $ROOTDIR/bin
		./container_connect
		echo -ne "${CYAN}Press enter to continue..${NC}"
                read
		cd -
		;;
	4)
		cd $ROOTDIR/bin
		./list_vpns
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	5)
		cd $ROOTDIR/bin
		[ -f .$SHOPCODE.ipsec.conf ] && ./stop_vpn || ./start_vpn
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	6)
		cd $ROOTDIR/bin
		./create_vpn
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	7)
		cd $ROOTDIR/bin
		./delete_vpn
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	s)
		cd $ROOTDIR/bin
		./set_working_shopcode
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	i)
		cd $ROOTDIR/bin
		./install
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
	p)
		cd $ROOTDIR/bin
		./prune-docker
		CONTAINER=`cat ./bin/.container 2>/dev/null`
		echo -ne "${CYAN}Press enter to continue..${NC}"
		read
		cd -
		;;
        r)
                cat README.md | more
                echo -ne "Press enter to continue..${NC}"
                read
                ;;
	x) exit ;;
	*) ;;
	esac
done
